#!/usr/bin/env ruby

DISKUTIL = "diskutil"
action = ARGV[0]
disk_name = ARGV[1]

def get_disk_id(name)
  begin
	  `diskutil list`.match(/#{name}\s*\*?[0-9]+\.[0-9]+ .B\s+(disk[0-9]s[0-9])$/)[1]
	rescue
	  exit 5
  end
end

if (action == 'mountpoint')
	puts File.join('', 'Volumes', disk_name, ARGV[2..-1])
else
  system DISKUTIL, action, get_disk_id(disk_name)
end