#!/usr/bin/env ruby

Commands = {
	"mount" => "mount",
	"unmount" => "umount"
}

DevicePaths = [
	"/dev/disk/by-label",
	"/dev/disk/by-uuid",
	"/dev"
]

action = ARGV[0]
disk_name = ARGV[1]

mountpoint = File.join('', 'mnt', disk_name)

if (action == 'mountpoint')
	puts File.join(mountpoint, ARGV[2..-1])
else
	puts "#{action.capitalize}ing #{mountpoint}..."
	system Commands[action], mountpoint

	if $?.exitstatus != 0 or $?.exitstatus != 3383
		exit 5
	end
end
